from io import StringIO
from typing import TextIO

text = """
04-11-2023 12:34:15.784559000 INFO: Author: Adrian Phung
04-11-2023 12:34:15.784575000 INFO: Copyright QRT 2023
04-11-2023 12:34:15.784578000 INFO: Application to simulate logging output of important production processes for use as part of the data feed analysis challenge
04-11-2023 12:34:15.784581000 INFO: durhack 2023
04-11-2023 12:34:15.784583000 INFO: The messages above must be included in all distributed files generated by this application.
04-11-2023 12:34:15.784586000 INFO: =============================================================================================================================
04-11-2023 12:34:15.784594000 ERROR: Receiving data a few usec slower now, microwave playing up again
04-11-2023 12:34:15.784599000 DEBUG: Received ping from server *Dragon*
04-11-2023 12:34:16.38296000 INFO: Sleeping for 414ms, because there is nothing to do
04-11-2023 12:34:16.38339000 DEBUG: Received heartbeat from exchange *Bishop*
04-11-2023 12:34:16.38344000 DEBUG: Sending keep alive to exchange *King*
04-11-2023 12:34:16.691424000 ERROR: Received Unknown error from exchange (Bishop), message: This should never happen, now we are in trouble!!!
04-11-2023 12:34:16.691476000 DEBUG: Sending keep alive to exchange *Bishop*
04-11-2023 12:34:16.691485000 DEBUG: Useless debug message, because dubug is full of these
04-11-2023 12:34:18.405707000 INFO: Received awake call from server [Dragon] with code [two]
04-11-2023 12:34:18.405750000 INFO: Creating additional connection object for exchange [King]
04-11-2023 12:34:18.405760000 DEBUG: Useless debug message, because dubug is full of these
04-11-2023 12:34:19.394821000 DEBUG: Received heartbeat from exchange *Rook*
04-11-2023 12:34:19.394862000 DEBUG: Sending keep alive to exchange *Knight*
04-11-2023 12:34:19.394872000 INFO: Creating additional connection object for exchange [Bishop]
04-11-2023 12:34:19.394881000 DEBUG: Recreating message with new code NEWC-213562
04-11-2023 12:34:20.516934000 ERROR: Unable to contact server (Phoenix), this keeps happening can someone from X team please fix this
04-11-2023 12:34:20.516976000 OTHER: Mathematics seems to endow one with something like a new sense - Darwin, Charles
04-11-2023 12:34:20.516986000 INFO: Aggregating tick from exchange [Rook] to [Dragon]
04-11-2023 12:34:20.516997000 DEBUG: Received ping from server *Dragon*
04-11-2023 12:34:20.517004000 INFO: Aggregating tick from exchange [Bishop] to [Unicorn]
04-11-2023 12:34:20.517012000 INFO: Received awake call from server [Griffin] with code [seven]
04-11-2023 12:34:20.517019000 INFO: Creating additional connection object for exchange [Knight]
04-11-2023 12:34:20.517026000 DEBUG: Received ping from server *Phoenix*
04-11-2023 12:34:20.517033000 DEBUG: Received heartbeat from exchange *Knight*
04-11-2023 12:34:20.517041000 DEBUG: Entering unimportant code area!!!
04-11-2023 12:34:21.344101000 DEBUG: Received ping from server *Griffin*
04-11-2023 12:34:21.344165000 OTHER: If you give a github repo in your CV make sure to have someone review the code, recruiters will look at the code
04-11-2023 12:34:21.344174000 OTHER: Let go, or be dragged - Zen Proverb
04-11-2023 12:34:21.401260000 OTHER: When your own life is threatened, your sense of empathy is blunted by a terrible, selfish hunger for survival
04-11-2023 12:34:21.934324000 DEBUG: Sending keep alive to exchange *Rook*
04-11-2023 12:34:21.934388000 OTHER: Have unit tests in your code on github listed on CV's it shows better software engineering
04-11-2023 12:34:21.934400000 INFO: Received awake call from server [Unicorn] with code [nine]
04-11-2023 12:34:21.956934000 WARN: Received out of order message from exchange {Knight}
04-11-2023 12:34:21.956957000 CRIT: Exchange <Knight>, issue received: This is bad!!!, this is above my pay grade we are going to lose alot of money because of this, i'm going to bail out!!!
04-11-2023 12:34:21.956965000 DEBUG: Received code: *two* what should i do with this?
04-11-2023 12:34:21.956973000 DEBUG: String processing of order *additional_info*
04-11-2023 12:34:21.956982000 DEBUG: Received ping from server *Griffin*
04-11-2023 12:34:22.868935000 OTHER: If you give a github repo in your CV make sure to have someone review the code, recruiters will look at the code
04-11-2023 12:34:24.414019000 DEBUG: Received heartbeat from exchange *Bishop*
04-11-2023 12:34:24.414067000 INFO: Sleeping for 37ms, because there is nothing to do
04-11-2023 12:34:24.414070000 DEBUG: Received heartbeat from exchange *Rook*
04-11-2023 12:34:24.414073000 DEBUG: Received heartbeat from exchange *King*
04-11-2023 12:34:26.56172000 DEBUG: Starting loop
04-11-2023 12:34:26.56213000 WARN: Received unexpected code {two} from server {Dragon}
04-11-2023 12:34:26.56219000 DEBUG: Recreating message with new code NEWC-3095
04-11-2023 12:34:26.56236000 ERROR: Receiving data a few usec slower now, microwave playing up again
04-11-2023 12:34:26.102162000 DEBUG: Pinging server *Unicorn*
04-11-2023 12:34:26.754714000 WARN: Unknown order {timing} from exchange {King}, notifying server {Unicorn}
04-11-2023 12:34:26.754754000 INFO: Aggregating tick from exchange [Bishop] to [Griffin]
04-11-2023 12:34:26.754758000 INFO: Creating additional connection object for exchange [Rook]
04-11-2023 12:34:26.754763000 DEBUG: Pinging server *Phoenix*
04-11-2023 12:34:26.754768000 OTHER: One must be deeply aware of the impermanence of the world.
04-11-2023 12:34:26.754772000 OTHER: When your own life is threatened, your sense of empathy is blunted by a terrible, selfish hunger for survival
04-11-2023 12:34:26.754776000 DEBUG: Finished loop
04-11-2023 12:34:26.754781000 ERROR: No message from exchange (Bishop) for over 04us, sending heartbeat and reconnection request
04-11-2023 12:34:26.994856000 DEBUG: Creating exchange message: *additional_info* for exchange *Bishop*
04-11-2023 12:34:26.994903000 INFO: Unable to commmunicate with transport from [Phoenix] for code [eight]
04-11-2023 12:34:26.994907000 DEBUG: Recreating message with new code NEWC-88
04-11-2023 12:34:26.994910000 DEBUG: Entering unimportant code area!!!
04-11-2023 12:34:26.994913000 INFO: Received awake call from server [Unicorn] with code [nine]
04-11-2023 12:34:26.994918000 ERROR: Received Unknown error from exchange (Bishop), message: This should never happen, now we are in trouble!!!
04-11-2023 12:34:26.994921000 DEBUG: Sending keep alive to exchange *Knight*
04-11-2023 12:34:26.994923000 DEBUG: Received heartbeat from exchange *Queen*
04-11-2023 12:34:26.994927000 ERROR: No message from exchange (Knight) for over 0168us, sending heartbeat and reconnection request
04-11-2023 12:34:26.994932000 OTHER: Mathematics seems to endow one with something like a new sense - Darwin, Charles
04-11-2023 12:34:28.644985000 INFO: Creating additional connection object for exchange [Queen]
04-11-2023 12:34:28.645030000 DEBUG: Finished loop
04-11-2023 12:34:28.645041000 DEBUG: Sending keep alive to exchange *Rook*
04-11-2023 12:34:28.645048000 INFO: Received awake call from server [Phoenix] with code [six]
04-11-2023 12:34:29.932055000 INFO: Sending order type [delete] to exchange [Queen]
04-11-2023 12:34:29.932104000 OTHER: Following good software engineering, ie have some unit tests, it'll save you so much time in the long run
04-11-2023 12:34:29.932110000 ERROR: Un-requested message from exchange (King): ooops this was not suppoed to happen, what are we supposed to do now!!!
04-11-2023 12:34:31.819515000 ERROR: Receiving data a few usec slower now, microwave playing up again
04-11-2023 12:34:31.819566000 INFO: Unable to commmunicate with transport from [Griffin] for code [three]
04-11-2023 12:34:31.819578000 DEBUG: Useless debug message, because dubug is full of these
04-11-2023 12:34:31.819588000 INFO: Received reponse from exchange [Bishop] for [add] with id [RSP-8724]
04-11-2023 12:34:31.819595000 DEBUG: Finished loop
04-11-2023 12:34:31.819604000 WARN: Unknown order {add} from exchange {Bishop}, notifying server {Griffin}
04-11-2023 12:34:31.819611000 DEBUG: Starting loop
04-11-2023 12:34:31.819617000 INFO: Received awake call from server [Dragon] with code [five]
04-11-2023 12:34:32.436125000 ERROR: Receiving data a few usec slower now, microwave playing up again
04-11-2023 12:34:32.436311000 INFO: Checking for consistency of processing times between [Unicorn] and [Dragon]
04-11-2023 12:34:32.436322000 ERROR: Receiving data a few usec slower now, microwave playing up again
04-11-2023 12:34:32.436331000 DEBUG: Finished loop
04-11-2023 12:34:33.917891000 INFO: Writing raw data to file for order code [four] message id: ORD-2096
04-11-2023 12:34:33.917951000 INFO: Checking for consistency of processing times between [Dragon] and [Phoenix]
04-11-2023 12:34:33.917961000 DEBUG: Finished loop
04-11-2023 12:34:33.917970000 INFO: Creating additional connection object for exchange [Queen]
04-11-2023 12:34:35.123530000 INFO: Starting batch mode for exchange [Queen]
04-11-2023 12:34:35.123564000 DEBUG: String processing of order *timing*
04-11-2023 12:34:35.123567000 INFO: Starting batch mode for exchange [Bishop]
04-11-2023 12:34:35.987613000 DEBUG: Starting loop
04-11-2023 12:34:35.987659000 DEBUG: Starting loop
04-11-2023 12:34:35.987677000 INFO: Aggregating tick from exchange [Queen] to [Unicorn]
04-11-2023 12:34:35.987685000 DEBUG: Entering unimportant code area!!!
04-11-2023 12:34:35.987695000 DEBUG: Creating exchange message: *timing* for exchange *Knight*
04-11-2023 12:34:35.987702000 DEBUG: Pinging server *Phoenix*
04-11-2023 12:34:35.987710000 INFO: Unable to commmunicate with transport from [Dragon] for code [four]
04-11-2023 12:34:35.987717000 DEBUG: String processing of order *update*
04-11-2023 12:34:35.987724000 INFO: Creating additional connection object for exchange [Knight]
04-11-2023 12:34:35.987734000 DEBUG: Received ping from server *Phoenix*
04-11-2023 12:34:36.963612000 INFO: Received awake call from server [Dragon] with code [three]
04-11-2023 12:34:36.963684000 INFO: Writing raw data to file for order code [one] message id: ORD-980785
04-11-2023 12:34:36.963693000 INFO: Creating additional connection object for exchange [Rook]
04-11-2023 12:34:36.963701000 DEBUG: Finished loop
04-11-2023 12:34:36.963708000 DEBUG: Received code: *one* what should i do with this?
04-11-2023 12:34:36.963714000 DEBUG: Finished loop
04-11-2023 12:34:36.963721000 DEBUG: Starting loop
04-11-2023 12:34:38.34783000 WARN: Unable to create order {timing} due to waiting batch response from exchange {Rook}
04-11-2023 12:34:38.34816000 INFO: Aggregating tick from exchange [King] to [Dragon]
04-11-2023 12:34:38.34826000 DEBUG: Sending keep alive to exchange *Knight*
04-11-2023 12:34:38.34836000 ERROR: Received Unknown error from exchange (Bishop), message: This should never happen, now we are in trouble!!!
04-11-2023 12:34:38.34845000 INFO: Writing raw data to file for order code [ten] message id: ORD-69
04-11-2023 12:34:38.34852000 DEBUG: Received heartbeat from exchange *Bishop*
04-11-2023 12:34:38.34861000 DEBUG: Received ping from server *Unicorn*
04-11-2023 12:34:39.563897000 ERROR: No message from exchange (Rook) for over 6718us, sending heartbeat and reconnection request
04-11-2023 12:34:41.330965000 DEBUG: String processing of order *additional_info*
04-11-2023 12:34:41.331005000 DEBUG: Received ping from server *Unicorn*
04-11-2023 12:34:41.331013000 DEBUG: Received ping from server *Griffin*
04-11-2023 12:34:41.331023000 INFO: Checking for consistency of processing times between [Phoenix] and [Griffin]
"""


def check_handle(f: TextIO):
    for line in f:
        print(line, end='')


with StringIO(text) as f:
    check_handle(f)